### PR TITLE
chore: Report min deployment version as semver string with every event

### PR DESCRIPTION
**Pull request by jnewc**
CHKT-1683

# What this PR does

Reports the minimum deployment target (i.e. min required OS version) of the integrating app.

# Instructions on how to test this

Inspect the event at runtime

# Before merging

_QA_

- [x] I manually tested this with a demo application (simulator)
- [x] I wrote unit tests for each new util-like function

### CODE REVIEW

**Comment by NQuinn27** [comment]
Forgive me if I am missing something - but I tested this using the Debug App, and it appears to report the min deployment version of the SDK, not the app itself - i.e, I see `po self.minDeploymentTarget "10.0.0"`. I would expect `13.1` in the Debug App

**Comment by jnewc** [comment]
@NQuinn27 you're correct. Unfortunately it looks like CocoaPods produces a different answer to the SPM project that I tested against (which returns the expected `12.0.0`).

I think the alternative route is to query the info.plist of the integrating project. I'll give it a try and see if it's more consistent.

**Comment by jnewc** [comment]
@NQuinn27 using `MinimumOSVersion` from the main bundle's info.plist works for both CocoaPods and SPM ✅

**Comment by NQuinn27** [comment]
> @NQuinn27 using `MinimumOSVersion` from the main bundle's info.plist works for both CocoaPods and SPM ✅

Nice, tested and looks good

**Review by NQuinn27 — APPROVED** [review]

**Pull request merged**
